app_name   = CALEYI
# possible values: DEBUG, INFO, WARNING, ERROR, FATAL
log_level  = DEBUG
app_port   = 9090
app_sql    = mysql

[mysql]
ip       =
port     =
user     =
password =
database =

[pgsql]
ip       =
port     =
user     =
password =
database =

[redis]
ip   = 127.0.0.1
port = 6379

[whitelist]
items =

[cors]
enable         = false
allow_origins  = *
allow_methods  = GET,POST,PUT,DELETE,PATCH,OPTIONS
allow_headers  = X-Requested-With,Content-Type,Authorization,BusinessId,verify-encrypt,ignoreCancelToken,verify-time,tenant_id
allow_credentials = true
max_age        = 12

[tenant]
auth = true